"""Pydantic v2 schema for Suspicious Activity Reports (SAR).

A SAR is generated by the SAR Generator agent only when the Decision
Synthesizer produces an `escalate` outcome. The structure mirrors the section
headers used in MASAK/FATF-aligned reports so the document stays compliant
even when downstream consumers render it as PDF.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class SARReport(BaseModel):
    """Structured Suspicious Activity Report.

    Generated by an LLM and validated against this schema. Failed structured
    output triggers a deterministic fallback that fills the report from
    `InvestigationResult` data so a SAR is always produced for escalated cases.
    """

    model_config = ConfigDict(frozen=True)

    transaction_id: str
    customer_info: dict[str, Any] = Field(
        default_factory=dict,
        description="Account holder identifiers and KYC fields available at decision time.",
    )
    transaction_details: dict[str, Any] = Field(
        default_factory=dict,
        description="Amount, currency, channel, counterparties, timestamps.",
    )
    suspicious_indicators: list[str] = Field(
        default_factory=list,
        description="Concrete red flags (e.g. circular flow, sanctions match, velocity anomaly).",
    )
    investigation_summary: str = Field(
        ...,
        description="Concise narrative of the agent's reasoning and evidence chain.",
    )
    regulatory_triggers: list[str] = Field(
        default_factory=list,
        description="Statutory references that mandate the filing (e.g. 'FATF Rec.13', 'MASAK Art.4').",
    )
    recommended_action: str = Field(
        ...,
        description="Next-step recommendation: file STR, freeze account, EDD, etc.",
    )
    generated_at: datetime
    agent_model: str = Field(
        ...,
        description="Model identifier that produced the SAR (e.g. claude-haiku-4-5).",
    )
