"""Capture real API outputs for all 50 gold_set cases and write demo/fixtures.py.

Usage:
    uv run python scripts/capture_fixtures.py

Requires the FraudLens API to be running at FRAUDLENS_API_BASE (default: http://localhost:8001/api/v1).
Output: demo/fixtures_captured.json  (raw captured data)
        demo/fixtures.py             (importable FIXTURES list)
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import time
from pathlib import Path

import httpx

_API_BASE = os.environ.get("FRAUDLENS_API_BASE", "http://localhost:8001/api/v1")
_POLL_INTERVAL = 2.0
_TIMEOUT = 180.0
_GOLD_SET = Path(__file__).parent.parent / "tests" / "eval" / "gold_set.jsonl"
_OUT_JSON = Path(__file__).parent.parent / "demo" / "fixtures_captured.json"
_OUT_PY = Path(__file__).parent.parent / "demo" / "fixtures.py"
_CONCURRENCY = 3  # parallel pipeline cap — respect LLM rate limits


async def _submit(client: httpx.AsyncClient, case: dict) -> str:
    raw_mode = case.get("raw_mode", False)
    url = f"{_API_BASE}/transactions"
    r = await client.post(url, json=case["transaction"], params={"raw_mode": raw_mode})
    r.raise_for_status()
    return r.json()["job_id"]


async def _poll(client: httpx.AsyncClient, job_id: str, case_id: str) -> dict:
    deadline = time.monotonic() + _TIMEOUT
    while time.monotonic() < deadline:
        r = await client.get(f"{_API_BASE}/jobs/{job_id}")
        r.raise_for_status()
        state = r.json()
        status = state["status"]
        if status == "done":
            return state["result"]
        if status == "error":
            raise RuntimeError(f"[{case_id}] pipeline error: {state.get('error')}")
        await asyncio.sleep(_POLL_INTERVAL)
    raise TimeoutError(f"[{case_id}] timed out after {_TIMEOUT}s")


async def _capture_one(
    sem: asyncio.Semaphore,
    client: httpx.AsyncClient,
    case: dict,
    idx: int,
    total: int,
) -> dict:
    case_id = case["case_id"]
    async with sem:
        t0 = time.monotonic()
        print(f"  [{idx}/{total}] {case_id} — submitting...", flush=True)
        job_id = await _submit(client, case)
        result = await _poll(client, job_id, case_id)
        elapsed_ms = (time.monotonic() - t0) * 1000
        print(f"  [{idx}/{total}] {case_id} — done ({elapsed_ms:.0f}ms)", flush=True)
        return {"case": case, "result": result, "elapsed_ms": elapsed_ms}


async def capture_all(cases: list[dict]) -> list[dict]:
    sem = asyncio.Semaphore(_CONCURRENCY)
    async with httpx.AsyncClient(timeout=30.0) as client:
        tasks = [
            _capture_one(sem, client, case, i + 1, len(cases))
            for i, case in enumerate(cases)
        ]
        return await asyncio.gather(*tasks)


def _write_py(fixtures: list[dict]) -> None:
    blob = json.dumps(fixtures, indent=2, ensure_ascii=False)
    content = (
        '"""Pre-captured API fixtures for HF Spaces demo (all 50 eval cases).\n'
        "\n"
        "Generated by scripts/capture_fixtures.py — do not edit manually.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "import json as _json\n"
        "\n"
        "_RAW = r'''\n"
        + blob
        + "\n'''\n"
        "\n"
        "FIXTURES: list[dict] = _json.loads(_RAW)\n"
    )
    _OUT_PY.write_text(content, encoding="utf-8")


def main() -> None:
    if not _GOLD_SET.exists():
        print(f"ERROR: gold_set not found at {_GOLD_SET}", file=sys.stderr)
        sys.exit(1)

    cases = [json.loads(line) for line in _GOLD_SET.read_text(encoding="utf-8").splitlines() if line.strip()]
    print(f"Loaded {len(cases)} cases from gold_set.jsonl")

    # Quick health check — /health is at the app root, not under /api/v1
    base_url = _API_BASE.split("/api/")[0]
    try:
        r = httpx.get(f"{base_url}/health", timeout=5)
        r.raise_for_status()
        print(f"API reachable at {_API_BASE}")
    except Exception as exc:
        print(f"ERROR: API not reachable — {exc}", file=sys.stderr)
        print("Start the API first: docker compose up -d  or  uv run uvicorn ...", file=sys.stderr)
        sys.exit(1)

    print(f"Capturing {len(cases)} cases (concurrency={_CONCURRENCY})...")
    t0 = time.monotonic()
    fixtures = asyncio.run(capture_all(cases))
    elapsed = time.monotonic() - t0
    print(f"\nCapture complete: {len(fixtures)} fixtures in {elapsed:.1f}s")

    _OUT_JSON.write_text(json.dumps(fixtures, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Raw JSON saved: {_OUT_JSON}")

    _write_py(fixtures)
    print(f"fixtures.py written: {_OUT_PY}")
    print("\nVerify with:")
    print("  python -c \"from demo.fixtures import FIXTURES; print(len(FIXTURES))\"")


if __name__ == "__main__":
    main()
